### ISSUE TITLE
cli-table: cell content truncation

### ISSUE THREAD

**Issue by rwaldron** [bterlson/eshost-cli#33]
Take a look: 

![](https://i.gyazo.com/601c6a7323dbefad5d4e2289fbed5808.png)

Of course the data is intact:

![](https://i.gyazo.com/d414ad224036f94540925b98056a6ebc.png)

...But I think this is not intuitive for eshost-cli's needs. 

I'm going to investigate alternatives.

**Comment by dilijev** [comment]
I noticed this when I was developing the initial feature. I managed to get it to behave somewhat before pushing, and I haven't seen the `...` since... It wasn't especially clear why `path` would be formatted to the widest entry but tags would not. At any rate, it's the behavior of the dependency library, which has a lot of options that behave in not quite the way you would want.

![image](https://user-images.githubusercontent.com/494055/28892375-9ffe3b52-7782-11e7-8016-e8376ce7d581.png)
